baseURL = 'https://thegraindance.alif4chan.workers.dev/'
languageCode = 'en-us'
title = 'The Grain Dance'
theme = 'ananke'

#Cover BG and Logo

[params]
    featured_image_class = "cover bg-center"
    custom_css = ["custom.css"]
    mainSections = ["opinion", "review", "diary", "others"]
    site_logo = "images/logo.png"

#Taxonomies

[taxonomies]
    category = "categories"
    tags = "tags"

#Social icons

[params.ananke.social.follow]
    networks =["instagram"]

[params.ananke.social.instagram]
    username = "javaboymk03"



#Menu 

[menu]
    [[menu.main]]
    name ="About"
    url = "/about/"
    weight = 10

    [[menu.main]]
    name = "Category"
    url = "/categories/"
    weight = 20

    [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 30
    
    [[menu.main]]
    name = "Lomography"
    url = "https://www.lomography.com/homes/javaboymk03/"
    weight = 40

#Cache
[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':cacheDir/images'
    maxAge = -1
  [caches.misc]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1

    #Privacy for instagram

    [privacy]
      [privacy.instagram]
      disable = false
      simple = false